name: ScuphUtils
version: 2.0
main: com.scuph.scuphsutilities.ScuphsUtilities
description: Scuph's utility plugin for LulzCraft!
authors: [Scuph]
commands:
    information:
        usage: /<command>
        description: Info about the plugin and server
        aliases: []
        permission: utils.info
    admins:
        usage: /<command>
        description: Find the server's admins
        aliases: administrators
        permission: utils.admins
    ban:
        usage: /ban <player> <reason>
        description: Ban a player
        aliases: utilsban
        permission: utils.ban    
    apply:
        usage: /<command>
        description: info on how to apply
        aliases: application
        permission: utils.apply
    requesthelp:
        usage: /<command>
        description: Request a staff member for help
        aliases: ineedhelp
        permission: utils.requesthelp
    owner:
        usage: /<command>
        description: Find the server's owner
        aliases: founder
        permission: utils.owner
    kick:
        usage: /kick <player> <reason>
        description: Kick a player
        aliases: utilskick
        permission: utils.kick
    warn:
        usage: /warn <player> <reason>
        description: Warn a player
        aliases: []
        permission: utils.warn    
        
        
